### ISSUE TITLE
Relation items not transferred through remoting?

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-orm#25]
```haxe
class User extends Object
{
	public var profile:HasOne<UserProfile>;
}
```

Say I have a `User` class which `HasOne` `UserProfile`. 
In my API, I have a get function to retrieve a user:

```haxe
// MyApi.hx
public function getUser(id:DatabaseID<User>):User 
{
  var user = User.manager.get(id);
  trace(user.profile); // call the getter to make sure profile is not null here at server-side
  return user;
}
```

And I wrap it as `class AsyncMyApi extends UFAsyncAPI<MyApi>`

```haxe
asyncMyApi.getUser(id).handle(function(user) trace(user.profile == null); 
// profile somehow became null at client side
```

So did I miss out any special handling about remoting which makes the profile becomes null across the internet?

**Comment by kevinresol** [comment]
Looking in to the `DBMacros` code, seems that only `ManyToMany` is being serialized? https://github.com/ufront/ufront-orm/blob/0503053589393c0a4285725fbb1e48c976347b3d/src/ufront/db/DBMacros.hx#L294

What is the rationale behind such decision?

**Comment by jasononeil** [comment]
See https://github.com/ufront/ufront-orm/commit/4b0df5de31ecac12532e18cc6fb93e6e9008ef91

And I just posted a comment to [here](https://github.com/ufront/ufront-mvc/issues/18#issuecomment-154326277), which I guess I should have posted here.

**Comment by jasononeil** [comment]
Copy/pasting from the discussion, to show what has been done, and what I want to finish for this issue to be considered "fixed". 

----

The first step I've just implemented in Ufront-ORM

- Be able to change which fields are included in serialization at runtime.  So you could serialize less fields, or more fields.
- For now that means editing the `hxSerializationFields` array:

```haxe
userProfile.hxSerializationFields.push( "user" ); // Include a BelongsTo<User> property
userProfile.user.hxSerializationFields = ["username","groups"]; // Include the ManyToMany<User,Group>
return userProfile;
```

In future I'll attempt a macro like...

```haxe
return BlogPost.manager.all().alsoWithFields([ author, author.name, author.id, tags[].name ]);
return BlogPost.manager.all().onlyWithFields([ title, url, author.name, author.id, tags[].name ]);
return User.manager.all().withoutFields([ password, salt ]);
```

...that is a type safe way of modifying `hxSerializationFields` on the relevant objects so you can easily pick which fields to return in your API.

**Comment by jasononeil** [comment]
The macro has been added by e4476b929904cbc72200e11f2d4bfe934ab83cf4

API Documentation is included [here](https://github.com/ufront/ufront-orm/blob/e4476b929904cbc72200e11f2d4bfe934ab83cf4/src/ufront/db/DBSerializationTools.hx#L43).
